### ISSUE TITLE
File writing renaming

### ISSUE THREAD

**Issue by cflynn3** [bp/ResSimpy#174]
Make the following changes in `FcsFile.py` to make following the code clearer

- [ ] Rename `update_fcs_file` to `update_model_files`
- [ ] Update the docstrings for `update_fcs_file` to make it clear that it updates the fcs file as well as all modified files in the model
- [ ] Add a comment around line 286 (before the for loops) explaining that we are looping through each file and writing out the contents

**Comment by MdSufiyan005** [comment]
Hey, can you please assign this to me
