### ISSUE TITLE
Nexus Wellspec files: Handle DTOP / DBOT

### ISSUE THREAD

**Issue by cflynn3** [bp/ResSimpy#197]
**Describe the bug**
Currently if a Nexus Wellspec table contains either DTOP or DBOT cards loading wells will fall over with the error `ValueError: could not convert string to float: 'TOP'`.

**To Reproduce**
1. Create a wellspec similar to:
```
WELLSPEC Well_1
IW  JW  L  KH RADW  SKIN WI DTOP DBOT
1 2 NA NA  0.3 0.00 NA TOP  BOT
```
2. Attempt to load in the wells information using `model.wells.get_wells_overview()`.

**Expected behavior**
The well is loaded in OK without error. To be decided if DTOP and DBOT should be added as properties to the Completion object.

**Screenshots**
N/A

**Additional context**
Unit tests to be created to test this behaviour as part of the fix.

**Comment by jonnyh404** [comment]
DTOP and DBOT are stored as floats in the depth_to_top and depth_to_bottom attributes. I think we should have separate attributes for when DTOP and DBOT are equal to strings such as depth_to_top_str and depth_to_bottom_str.
